bar {
	status_command i3blocks -c ~/.config/i3blocks/i3blocks.conf
	separator_symbol " "
	font pango:BigBlueTerm437 Nerd Font Mono Bold 8
	output primary
	colors {
		   background #282828
		   focused_workspace #98971a #98971a #282828
		   inactive_workspace #282828 #282828 #a89984
		   urgent_workspace #cc241d #cc241d #282828
	}
}

font pango:BigBlueTerm437 Nerd Font Mono Regular 8
workspace_layout default

for_window [class="^.*"] border pixel 0
default_border pixel 0

gaps inner 0
gaps outer 0

hide_edge_borders both

# color settings fo windows
set $color1     #282828
set $color2     #98971a
set $color3     #cc241d
#app_id                          border          bground         text            indicator       child_border
client.focused               $color2           $color2         $color1           $color2         $color2
client.unfocused             $color2           $color1         $color2           $color1         $color1
client.focused_inactive      $color2           $color1         $color2           $color1         $color1
client.urgent                $color3           $color3         $color1           $color3         $color1
