# ── Font ─────────────────────────────────────────────────────────────────────
font_family      BigBlueTerm437NerdFont
font_size        13.0

# ── Cursor ───────────────────────────────────────────────────────────────────
cursor_shape           block
cursor_blink_interval  0.2
cursor_stop_blinking_after 0

# ── Window ───────────────────────────────────────────────────────────────────
background_opacity     1
hide_window_decorations yes

# ── Scrollback ────────────────────────────────────────────────────────────────
scrollback_lines     10000
listen_on unix:/tmp/kitty
shell_integration enabled
action_alias kitty_scrollback_nvim kitten $HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

# ── Clipboard ────────────────────────────────────────────────────────────────
copy_on_select         yes
strip_trailing_spaces  always

# ── Tabs & Splits ────────────────────────────────────────────────────────────
tab_bar_min_tabs 1
tab_title_template "[{title.upper()}]"
tab_bar_style separator
tab_separator ""
tab_bar_margin_width 0.0
tab_title_max_length 15
active_tab_font_style   normal
active_tab_foreground   #282828
active_tab_background   #98971a
inactive_tab_foreground #98971a
inactive_tab_background #282828
tab_bar_background      #282828

enabled_layouts splits,stack

map ctrl+shift+t  new_tab_with_cwd
map ctrl+shift+b  launch --cwd=current --location=vsplit
map ctrl+shift+s  launch --cwd=current --location=hsplit
map ctrl+shift+f  toggle_layout stack
map ctrl+shift+h  neighboring_window left
map ctrl+shift+l  neighboring_window right
map ctrl+shift+k  neighboring_window up
map ctrl+shift+j  neighboring_window down
map ctrl+shift+r  start_resizing_window
map ctrl+shift+w  close_window
map ctrl+|        kitty_scrollback_nvim
map ctrl+t        no_op

# ── Shell integration ────────────────────────────────────────────────────────
shell_integration no-cursor

# ── Close confirmation ───────────────────────────────────────────────────────
confirm_os_window_close 0

# Gruv
include gruv.conf

allow_remote_control yes
graphics_protocol kitty
