[colors]
[colors.primary]
foreground = "#e2cca9"
background = "#252423"

[colors.normal]
black = "#32302f"
red = "#db4740"
green = "#b0b846"
yellow = "#f28534"
blue = "#80aa9e"
magenta = "#d3869b"
cyan = "#8bba7f"
white = "#e2cca9"

[colors.bright]
black = "#5a524c"
red = "#f2594b"
green = "#b0b846"
yellow = "#e9b143"
blue = "#80aa9e"
magenta = "#d3869b"
cyan = "#8bba7f"
white = "#e2cca9"
