[colors]
[colors.primary]
foreground = "#9eacad"
background = "#00141a"

[colors.dim]
red = "#b7221e"
green = "#596600"
yellow = "#cb4a15"
blue = "#1a6497"
magenta = "#b02669"
cyan = "#196265"
white = "#9eacad"

[colors.normal]
black = "#012b36"
red = "#dc322f"
green = "#859901"
yellow = "#f8520e"
blue = "#278bd2"
magenta = "#d43682"
cyan = "#2aa198"
white = "#adb8b8"

[colors.bright]
black = "#063642"
red = "#f6524f"
green = "#bafb00"
yellow = "#ffc102"
blue = "#48aef5"
magenta = "#f255a1"
cyan = "#27eee0"
white = "#eee8d5"
